# Generated by Django 4.2.28 on 2026-03-15 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_role", models.CharField(blank=True, max_length=20)),
                ("user_name", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("user_register", "User Register"),
                            ("user_suspended", "User Suspended"),
                            ("user_activated", "User Activated"),
                            ("user_deleted", "User Deleted"),
                            ("report_submitted", "Report Submitted"),
                            ("report_approved", "Report Approved"),
                            ("report_rejected", "Report Rejected"),
                            ("report_restored", "Report Restored"),
                            ("report_deleted", "Report Deleted"),
                            ("center_created", "Center Created"),
                            ("center_updated", "Center Updated"),
                            ("center_deleted", "Center Deleted"),
                            ("center_deactivated", "Center Deactivated"),
                            ("center_reactivated", "Center Reactivated"),
                            ("route_calculated", "Route Calculated"),
                            ("navigation_started", "Navigation Started"),
                            ("navigation_completed", "Navigation Completed"),
                            ("system_startup", "System Startup"),
                            ("system_error", "System Error"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("user_management", "User Management"),
                            ("hazard_reports", "Hazard Reports"),
                            ("evacuation_centers", "Evacuation Centers"),
                            ("navigation", "Navigation"),
                            ("system", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("related_object_type", models.CharField(blank=True, max_length=100)),
                ("related_object_id", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_systemlog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="system_syst_created_0b5d70_idx"
                    ),
                    models.Index(
                        fields=["user"], name="system_syst_user_id_bb1873_idx"
                    ),
                    models.Index(
                        fields=["action"], name="system_syst_action_5e90e7_idx"
                    ),
                    models.Index(
                        fields=["module"], name="system_syst_module_030a38_idx"
                    ),
                    models.Index(
                        fields=["status"], name="system_syst_status_0d0b04_idx"
                    ),
                ],
            },
        ),
    ]
