# Generated by Django 5.2.3 on 2026-02-07 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evacuation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("start_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("end_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("end_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("base_distance", models.FloatField(default=0)),
                ("predicted_risk_score", models.FloatField(default=0)),
            ],
            options={
                "db_table": "routing_roadsegment",
            },
        ),
        migrations.CreateModel(
            name="RouteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_route_risk", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evacuation_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_logs",
                        to="evacuation.evacuationcenter",
                    ),
                ),
            ],
            options={
                "db_table": "routing_routelog",
            },
        ),
    ]
