# Generated by Django 4.2.28 on 2026-02-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadsegment",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
