# Generated by Django 4.2.28 on 2026-02-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hazards", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hazardreport",
            name="admin_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hazardreport",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]
