# Generated by Django 4.2.28 on 2026-03-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hazards", "0005_hazardreport_validation_breakdown"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hazardreport",
            options={"ordering": ["-created_at"]},
        ),
    ]
