# Generated by Django 4.2.28 on 2026-03-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hazards", "0008_hazardreport_public_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="hazardreport",
            name="distance_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hazardreport",
            name="final_validation_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
