from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0011_hazardreport_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='client_submission_id',
            field=models.CharField(
                max_length=64,
                blank=True,
                null=True,
                db_index=True,
                help_text=(
                    'UUID generated by the mobile client before submission. '
                    'Used to detect duplicate uploads when the same offline report is re-synced. '
                    'Null for reports submitted while online.'
                ),
            ),
        ),
    ]
