# Generated by Django 4.2.28 on 2026-02-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evacuation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evacuationcenter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
