# Generated by Django 4.2.28 on 2026-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evacuation", "0002_evacuationcenter_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="evacuationcenter",
            name="barangay",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="evacuationcenter",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="evacuationcenter",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="evacuationcenter",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evacuationcenter",
            name="is_operational",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evacuationcenter",
            name="municipality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="evacuationcenter",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="evacuationcenter",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="evacuationcenter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
